Map<String, String> en = {
//공통
//회원가입

  '이메일': 'E-mail',
  '비밀번호': 'Password',
  '로그인': 'Login',
  '비밀번호를_잊으셨나요': 'Forget password?',
  '비밀번호_찾기': 'Find password',
  '페이스북으로_로그인': 'Sign in with Facebook',
  '아직_회원이_아니신가요': 'Not a member yet?',
  '회원가입': 'Register',
  '계정을_생성해주세요': 'Please create an account',
  '비밀번호_재확인': 'Re-confirm password',
  '파인드어스_이용약관_필수': 'Terms of service for Findus',
  '파인드어스_개인정보_수집_동의_필수': 'Privacy policy for Findus',
  '비밀번호가_양식에_맞지_않습니다': 'Password format is not correct',
  '이미_등록된_이메일입니다': 'This email has already been registered',
  '해당_계정의_비밀번호를_변경합니다': 'Change the password for that account',
  '이메일_인증': 'Email Authentication',
  '인증확인': 'Verify email',
  '다음': 'Next',
  '새_비밀번호를_입력해주세요': 'Please enter a new password',
  '축하드립니다': 'Welcome for Findus',
  '비밀번호_재설정이_완료되었습니다': 'Password reset completed',
  '확인': 'Confirm',
  '알림': 'Notice',
  '비밀번호_재_설정이_완료되었습니다__로그인을_해주세요': 'Password reset completed.Please log in',
  '등록되지_않은_이메일입니다': 'This is an unregistered email',
  '비밀번호가_틀렸습니다': 'Password is incorrect.',
  '유저네임에_들어갈_수_없습니다': 'Unable to enter user name',
  '유저네임에_한글이나_특수_문자가_들어갈_수_없습니다':
      'User name cannot contain Korean or special characters',
  '유저네임의_길이를_초과하였습니다': 'User name length exceeded',
  '유저네임의_최소_길이는_3자입니다': 'Minimum length of username is 3 characters',
  '패스워드_공백이_들어갈_수_없습니다': 'Password spaces cannot enter',
  '패스워드의_길이를_초과하였습니다': 'Password length exceeded',
  '패스워드의_최소_길이는_4자입니다': 'Password minimum length is 4 characters',
  '이메일은_공백이_들어갈_수_없습니다': 'Email cannot contain spaces',
  '이메일_형식에_맞지_않습니다': 'Email format is not correct',
  '이메일을_입력해주세요': 'Please enter email',
  '메일이_전송되었습니다.\n메일을_확인후_비밀번호를_변경해주세요':
      'A verification email has been sent.\n Please change your password after clicking the email verification link.',
  '이메일은_필수사항_입니다': 'Email is required',
  '잘못된_이메일_형식입니다': 'Incorrect email format',
  '양식에_맞지_않습니다': 'Account form is not correct.',
  '비밀번호가_다릅니다': 'Password does not match.',
  '비밀번호가_양식에_맞지않습니다': 'Password is out of form',
  '비밀번호_변경': 'Change Password',
  '재설정_이메일_전송': 'Send reset email',
  '이용약관은_필수_사항입니다': 'Terms of use is required.',

  '인증_메일을_발송하였습니다': 'A verification email has been sent.',
  '메일을_확인_후_인증을_진행해_주세요': 'Please check the email and proceed with.',
  '인증을_하지_않을_시_회원가입이_완료되지_않습니다':
      'If you do not authenticate,  registration will not be completed.',
  '인증_메일을_발송하였습니다_메일을_확인_후_링크를_눌러서비밀번호를_설정해주세요':
      'A verification email has been sent.\nCheck your email and click the link Please set a password.',
  '동의': 'Agree',

//지도

  '관심있는_장소_검색': 'Search location',
  '검색어를_입력해주세요': 'Please enter a search keyword',
  '음식점': 'Restaurant',
  '노래방': 'Karaoke',
  '국제배송__카르고': 'Shipping.',
  '핸드폰': 'Cell phone store',
  '미용실:': 'Hair salon',
  '할인매장': 'Outlet',
  '영업중': 'Open',
  '마감': 'Close',
  '복사': 'Copy',
  '월요일': 'Mon',
  '화요일': 'Tue',
  '수요일': 'Wed',
  '목요일': 'Thu',
  '금요일': 'Fri',
  '토요일': 'Sat',
  '일요일': 'Sun', //월~금까지_필요
  '가게상세': 'Details',
  '영업_시작': 'Open',
  '마감시간': 'End time',
  '복사_완료': 'Copy Complete',
  '123층': 'rd floor',
  '층': 'th floor',
  '호': '',

//게시판
//TODO:_DB_-_게시판목록(자유게시판,_비자게시판,_일자리게시판_몽골어_번역_필요)
//TODO:_DB_-_지역(서울,충주)_업종(컨테이너,_고깃집)_번역_필요

  '전체': 'All',
  '인기': 'Best',
  '신고': 'Report',
  '마감_게시판': 'Finished',
  '내가_쓴_글': 'My write',
  '내가_쓴_공고': 'My write for job',
  '자유_게시판': 'Notice board',
  '비자_게시판': 'Visa information',
  '댓글을_입력해주세요': 'Please enter a comment',
  '편집': 'Edit',
  '삭제': 'Delete',
  '게시물이_없습니다': 'There are no posts',
  '글쓰기': 'Write',
  '등록': 'Confirm',
  '제목을_입력해주세요': 'Please enter a post title',
  '내용을_입력해주세요__10글자_이상': 'Please enter the contents More than 10 characters',
  '게시글이_등록되었습니다': 'Post has been registered',
  '게시글이_수정되었습니다': 'Post has been edited',
  '최신순': 'Newest',
  '검색어를_입력해주세요_게시판': 'Please enter a search keyword.',
  '모집중': 'Recruiting',
  '모집중_2': 'Recruiting',
  '일당': 'Pay',
  '일자리': 'Work',
  '지원하기': 'Apply for',
  '채용정보': 'Work information',
  '근무지역': 'Work area',
  '업종': 'Work industry',
  '연락처': 'Contact',
  '문자_보내기': 'Send sms',
  '전화걸기': 'Make a call',
  '상세요강': 'Details',
  '마감하기': 'Close',
  '댓글이_작성되었습니다': 'Comment has been registered',
  '댓글을_삭제하시겠습니까': 'Delete your comment?',
  '네': 'Yes',
  '아니오': 'No',
  '삭제된_댓글': 'Comment deleted',
  '댓글이_삭제되었습니다': 'Comment has been deleted',
  '지역을_선택해주세요': 'Please select a region',
  '업종을_선택해주세요': 'Please select an industry',
  '기타': 'Etc.',
  '검색하기': 'Search',
  '주소': 'Address',
  '주소를_검색해주세요': 'Please search address',
  '상세_주소를_입력해주세요': 'Please enter detailed address',
  '마감일': 'Deadline',
  '알림_게시판': 'Notice',
  '제목을_입력해주세요_알림': 'Please enter a post title',
  '내용을_입력해주세요_알림': 'Please enter the contents',
  '지역을_선택해주세요_알림': 'Please select a region',
  '업종을_선택해주세요_알림': 'Please select an industry',
  '핸드폰_번호를_입력해주세요_알림': 'Please enter your phone number',
  '주소를_입력해주세요_알림': 'please enter address',
  '상세주소를_입력해주세요_알림': 'Please enter detailed address',
  '공고가_등록되었습니다': 'Job advertisement has been uploaded',
  '공고가_수정되었습니다': 'Job advertisement has been edited',
  '모집글_작성': 'Recruitment',
  '댓글엔_공백이_들어갈_수_없습니다': 'Only spaces cannot be entered.',
  '제목은_공백이_들어갈_수_없습니다': 'Only spaces cannot be entered.',
  '내용은_공백이_들어갈_수_없습니다': 'Only spaces cannot be entered.',
  '28자_이내로_작성해주세요': 'Please write it in 28 characters or less',
  '내용의_길이를_초과하였습니다': 'Content length exceeded',
  '본문은_10글자_이상_입력해주세요': 'Please enter at least 10 characters for the text',
  '전화번호는_공백이_들어갈_수_없습니다': 'Only spaces cannot be entered.',
  '전화번호_형식에_맞지_않습니다': 'Invalid phone number format.',
  '원': 'KRW',
  '일당을_입력해주세요': 'Please enter the pay.',
  '전화번호': 'Contact',
  '삭제_완료': 'Deleted.',
  '관심있는_글_검색': 'Search',
  '관심있는_일자리_검색': 'Search',
  '허위글_신고하기': 'Report',
  '지도로보기': 'View on map',
  '취소': 'Cancel',
  '선택': 'Select',
  '사용자_차단': 'User block',
  '유저를_차단하면_해당_유저가_올린_글을_볼수_없게_됩니다_차단_하시겠습니까':
      'If you block this user, you will not be able to see their posts. Do you want to block it?',
  '차단_해제': 'Unblock',
  '차단_되었습니다': 'Has been blocked.',
  '사용자를_차단_하시겠습니까': 'Block that user?',
  '차단_목록': 'Blocked list',
  '차단_해제되었습니다': 'User is unblocked.',

//설정
  '프로필_설정': 'Profile',
  '앨범에서_선택': 'Gallery',
  '사진촬영': 'Camera',
  '저장_설정': 'Save',
  '닉네임이_저장되었습니다': 'Nickname has been saved',
  '3글자_이상_입력할_수_없습니다': 'Cannot enter more than 3 characters',
  '언어_설정': 'Language', //언어설정_아이콘_필요
  '로그아웃': 'Log-out',
  '프로필_사진_편집': 'Edit',
  '닉네임': 'Nickname',
  '이메일_설정': 'Email',
  '프로필': 'Profile',
  '저장': 'Save',
  '정말로_로그아웃_하시겠습니까': 'Are you want to log out?',
  '약관_및_정책': 'Terms & Policies',
  '서비스_이용_약관': 'Terms of Service',
  '개인정보_처리_방침': 'Хэрэглэгчдийн заалт',

//신고
  '이_글을_신고하시겠습니까': 'Are you want to report this post?',
  '신고하실_내용을_적어주세요': 'Please write your report.',
  '신고_버튼': 'Report',
  '취소_버튼': 'Cancel',
  '신고가_정상적으로_접수되었습니다': 'Successfully received.',

//문의
  '문의하기': 'Feedback',
  '무엇을_도와드릴까요': 'How can I help you?',
  'Findus_관리자에게_직접_문의해보세요': 'Contact the findus operator directly!',
  '사용_중_궁금한_점,개선되어야할_점이_있다면_언제든지_문의해주세요\n비즈니스_관련_문의도_받습니다':
      'If you have any questions or improvements during use,\nplease feel free to contact us.\nWe also accept business-related inquiries.',
  '문의_내용을_입력해주세요': 'Please enter your inquiry details.',
  '문의하기_버튼': 'Send',
};
